# Investor - Flow of Funds - US

### Introduction:

Special thanks to: https://github.com/rgrp for sharing the dataset.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/datasets/investor-flow-of-funds-us/master/data/weekly.csv).

### Step 3. Assign it to a variable called

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/datasets/investor-flow-of-funds-us/master/data/weekly.csv")
df.head()

,Date,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
0,2011-10-05,-4002,-4499.0,497,-1354.0,-5828,-6258.0,430,-11184.0
1,2011-10-12,-7397,-5842.0,-1555,512.0,3954,3927.0,28,-2931.0
2,2011-10-19,-3292,-3466.0,174,1399.0,5652,5102.0,550,3759.0
3,2011-10-26,-3696,-2998.0,-698,2631.0,4910,4070.0,841,3846.0
4,2011-12-07,-7956,-5761.0,-2196,1089.0,3523,2068.0,1456,-3343.0

### Step 4.  What is the frequency of the dataset?

In [4]:
df.value_counts().sum()

50

### Step 5. Set the column Date as the index.

In [5]:
df = df.set_index('Date')

In [6]:
df

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2011-10-05,-4002,-4499.0,497,-1354.0,-5828,-6258.0,430,-11184.0
2011-10-12,-7397,-5842.0,-1555,512.0,3954,3927.0,28,-2931.0
2011-10-19,-3292,-3466.0,174,1399.0,5652,5102.0,550,3759.0
2011-10-26,-3696,-2998.0,-698,2631.0,4910,4070.0,841,3846.0
2011-12-07,-7956,-5761.0,-2196,1089.0,3523,2068.0,1456,-3343.0
...,...,...,...,...,...,...,...,...
2024-12-04,27170,NaN,22014,NaN,22510,NaN,-496,NaN
2024-12-11,36551,NaN,28883,NaN,29251,NaN,-368,NaN
2024-12-18,23053,NaN,27124,NaN,20767,NaN,6358,NaN
2024-12-24,35211,NaN,36142,NaN,32529,NaN,3613,NaN
2024-12-31,26027,NaN,21578,NaN,19932,NaN,1646,NaN

### Step 6. What is the type of the index?

In [9]:
df.index.dtype

#object

dtype('O')

### Step 7. Set the index to a DatetimeIndex type

In [10]:
df.index = pd.to_datetime(df.index)
df.index

DatetimeIndex(['2011-10-05', '2011-10-12', '2011-10-19', '2011-10-26',
               '2011-12-07', '2011-12-14', '2011-12-21', '2011-12-28',
               '2012-12-05', '2012-12-12',
               ...
               '2024-06-26', '2024-07-02', '2024-07-10', '2024-07-17',
               '2024-07-24', '2024-12-04', '2024-12-11', '2024-12-18',
               '2024-12-24', '2024-12-31'],
              dtype='datetime64[ns]', name='Date', length=159, freq=None)

### Step 8.  Change the frequency to monthly, sum the values and assign it to monthly.

In [11]:
monthly = df.resample("M").sum()
monthly

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2011-10-31,-18387,-16805.0,-1582,3188.0,8688,6841.0,1849,-6510.0
2011-11-30,0,0.0,0,0.0,0,0.0,0,0.0
2011-12-31,-23657,-16659.0,-6999,2395.0,13817,9335.0,4483,-7443.0
2012-01-31,0,0.0,0,0.0,0,0.0,0,0.0
2012-02-29,0,0.0,0,0.0,0,0.0,0,0.0
...,...,...,...,...,...,...,...,...
2024-08-31,0,0.0,0,0.0,0,0.0,0,0.0
2024-09-30,0,0.0,0,0.0,0,0.0,0,0.0
2024-10-31,0,0.0,0,0.0,0,0.0,0,0.0
2024-11-30,0,0.0,0,0.0,0,0.0,0,0.0
2024-12-31,148012,0.0,135741,0.0,124989,0.0,10753,0.0

### Step 9. You will notice that it filled the dataFrame with months that don't have any data with NaN. Let's drop these rows.

In [18]:
df.isna().sum()

Total Equity         0
Domestic Equity    109
World Equity         0
Hybrid             109
Total Bond           0
Taxable Bond       109
Municipal Bond       0
Total              109
dtype: int64

In [19]:
monthly = monthly[monthly!=0]

In [21]:
monthly = monthly.dropna()
monthly

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2011-10-31,-18387.0,-16805.0,-1582.0,3188.0,8688.0,6841.0,1849.0,-6510.0
2011-12-31,-23657.0,-16659.0,-6999.0,2395.0,13817.0,9335.0,4483.0,-7443.0
2012-12-31,-23929.0,-22012.0,-1915.0,785.0,9828.0,12491.0,-2663.0,-13316.0
2013-12-31,8052.0,-5562.0,13615.0,4180.0,-24460.0,-14209.0,-10251.0,-12227.0
2014-12-31,-17011.0,-15124.0,-1887.0,-6141.0,-14400.0,-19014.0,4614.0,-37552.0
2015-12-31,-36337.0,-25116.0,-11221.0,-12474.0,-28678.0,-34571.0,5893.0,-77489.0
2017-01-31,-16148.0,-16362.0,214.0,-3621.0,14983.0,13870.0,1113.0,-4785.0
2017-12-31,-35122.0,-38565.0,3443.0,-6893.0,11175.0,12490.0,-1317.0,-30840.0
2019-01-31,97.0,1372.0,-1275.0,-5665.0,-1184.0,-8324.0,7140.0,-6752.0
2019-12-31,-58297.0,-50202.0,-8095.0,-5209.0,38491.0,28810.0,9680.0,-25014.0
2020-12-31,-66618.0,-40387.0,-26231.0,-2972.0,60423.0,50781.0,9643.0,-9170.0

### Step 10. Good, now we have the monthly data. Now change the frequency to year.

In [22]:
year = monthly.resample('AS-JAN').sum()
year

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2011-01-01,-42044.0,-33464.0,-8581.0,5583.0,22505.0,16176.0,6332.0,-13953.0
2012-01-01,-23929.0,-22012.0,-1915.0,785.0,9828.0,12491.0,-2663.0,-13316.0
2013-01-01,8052.0,-5562.0,13615.0,4180.0,-24460.0,-14209.0,-10251.0,-12227.0
2014-01-01,-17011.0,-15124.0,-1887.0,-6141.0,-14400.0,-19014.0,4614.0,-37552.0
2015-01-01,-36337.0,-25116.0,-11221.0,-12474.0,-28678.0,-34571.0,5893.0,-77489.0
2016-01-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-01-01,-51270.0,-54927.0,3657.0,-10514.0,26158.0,26360.0,-204.0,-35625.0
2018-01-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-01-01,-58200.0,-48830.0,-9370.0,-10874.0,37307.0,20486.0,16820.0,-31766.0
2020-01-01,-66618.0,-40387.0,-26231.0,-2972.0,60423.0,50781.0,9643.0,-9170.0

### BONUS: Create your own question and answer it.